language: node_js
node_js:
 - 12.16.1
cache: yarn

install:
 - yarn install

addons:
  chrome: stable
script:
 - yarn test
 - yarn run build

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 local_dir: dist
 on:
  branch: master
